Vacations/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vacations.Models
{
    public class Request
    {
        public int requestId { get; set; }

        [Required(ErrorMessage="State must be specified")]
        public string state { get; set; }

        [Required(ErrorMessage = "Description must be specified")]
        public string description { get; set; }


        public int daysRequestedCount { get; set; }
        public int midDaysCount { get; set; }
        public int PersonpersonaId { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public int createdBy { get; set; }
        public int updatedBy { get; set; }

    }
}

Vacations/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vacations.Controllers
{
   // [Authorize]
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Profile()
        {
            return View();
        }
    }
}

Vacations/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vacations;
using Vacations.Models;


namespace Vacations.Controllers
{
    public class RequestController : Controller
    {
        private EntitiesVacation db = new EntitiesVacation();
        List<RequestDTO> requestToFind = new List<RequestDTO>();

        public ActionResult Serve()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }


        public ActionResult FilterRequest(string state)
        {

            List<RequestDTO> listStateRequest = new List<RequestDTO>();

            int idPerson = (int)this.Session["idUser"];
            requestToFind = getRequestDetailsByPerson(idPerson);

            listStateRequest = GetRequestByState(state, requestToFind);

            ViewData.Model = listStateRequest;

            return View();
        }

        public ActionResult MyVacation()
        {

            int idPerson = (int)this.Session["idUser"];
            requestToFind = getRequestDetailsByPerson(idPerson);

            ViewData.Model = requestToFind;


            return View();
        }

        public ActionResult UpdateDates()
        {
            List<HoliDays> holiDays = db.HoliDays.ToList();
            List<DateTime> holidates = new List<DateTime>();
            for (int i = 0; i < holiDays.Count; i++)
            {
                holidates.Add(holiDays.ElementAt(i).date);
            }
            ViewData["holidaysDate"] = holiDays;
            ViewBag.holidaysDate = holiDays;
            ViewBag.holidates = holidates;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateDates(String days)
        {
            if (ModelState.IsValid)
            {
                List<DateModel> daysRequested = StringToList(days);
                TempData["days"] = daysRequested.ToList();

            }
            return RedirectToAction("UpdateCheck");
        }

        //GET
        public ActionResult UpdateCheck()
        {
            List<DateModel> model = TempData["days"] as List<DateModel>;

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCheck(List<DateModel> model)
        {

            DateModel dateModel;
            List<TurnModel> turn;

            List<Day> daysRequested = new List<Day>();
            Day day = new Day();
            int fullDaysCount = 0;
            int midDaysCount = 0;


            //El sgte ciclo agarra los dias del modelo para crear una lista de Days con sus respectivos turnos
            //Realiza el conteo de los medios dias y dias completos para llenar la tabla request
            for (int index = 0; index < model.Count; index++)
            {
                dateModel = new DateModel();
                turn = new List<TurnModel>();
                dateModel = model.ElementAt(index);
                turn = dateModel.turn;

                day = new Day();

                if (turn.ElementAt(0).isChecked && turn.ElementAt(1).isChecked && turn.ElementAt(2).isChecked)
                {
                    day.turn = 1;
                    fullDaysCount++;

                }
                else if (turn.ElementAt(0).isChecked && !turn.ElementAt(1).isChecked && !turn.ElementAt(2).isChecked)
                {
                    day.turn = 2;
                    midDaysCount++;

                }
                else if (!turn.ElementAt(0).isChecked && turn.ElementAt(1).isChecked && !turn.ElementAt(2).isChecked)
                {
                    day.turn = 3;
                    midDaysCount++;
                }
                else if (!turn.ElementAt(0).isChecked && !turn.ElementAt(1).isChecked && turn.ElementAt(2).isChecked)
                {
                    day.turn = 4;
                    midDaysCount++;
                }
                else
                {
                    ViewBag.Message = "Ingrese los turnos correctamente, marque solo un turno o los tres";
                    return View("Check", model);
                }

                day.day1 = dateModel.date;
                day.createdAt = DateTime.Now;
                day.updatedAt = DateTime.Now;
                day.createdBy = (int)Session["identification"];
                day.updatedBy = (int)Session["identification"];
                daysRequested.Add(day);



            };

            Request request = new Request();
            request.state = "sent";
            request.description = "TESTING";
            request.daysRequestedCount = fullDaysCount;
            request.midDaysCount = midDaysCount;
            request.PersonpersonaId = (int)Session["idUser"];
            request.createdAt = DateTime.Now;
            request.updatedAt = DateTime.Now;
            request.updatedBy = (int)Session["identification"];

            int payrollId = (int)Session["payrollId"];
            fullDaysCount += midDaysCount / 2;

            Payroll payroll = new Payroll();
            payroll = db.Payroll.First(p => p.RolId == payrollId);


            if (fullDaysCount > payroll.availableDays)
            {
                return RedirectToAction("Create", new { message = "Cuenta con " + payroll.availableDays + " día(s) disponible(s), ingrese los datos nuevamente" });

            }
            else
            {
                //decrementDays(payroll, fullDaysCount);



                updateRequest(request);
                deleteOldDays(request.requestId);   
                


                ViewBag.Message = "sent";
                return View(model);

            }

            return PartialView("Confirm");

        }


        public ActionResult Create(string message = "")
        {
            ViewBag.Message = message;
            List<HoliDays> holiDays = db.HoliDays.ToList();
            List<DateTime> holidates = new List<DateTime>();
            for (int i = 0; i < holiDays.Count; i++)
            {
                holidates.Add(holiDays.ElementAt(i).date);
            }
            ViewData["holidaysDate"] = holiDays;
            ViewBag.holidaysDate = holiDays;
            ViewBag.holidates = holidates;
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "requestId,state,description,daysRequestedCount,midDaysCount,PersonpersonaId,createdAt,updatedAt,createdBy,updatedBy, justificacion")] Request request, String days)
        {


            if (ModelState.IsValid)
            {
                System.Diagnostics.Debug.WriteLine(request.justificacion);

                List<DateModel> daysRequested = StringToList(days);
                TempData["justif"] = request.justificacion;
                TempData["days"] = daysRequested.ToList();
            }
            return RedirectToAction("Check");
        }


        public List<DateModel> StringToList(string days)
        {
            days = days.Replace(" ", "");
            string[] parts = days.Split(',');
            List<DateModel> StringToList = new List<DateModel>();
            DateModel date;

            for (int i = 0; i < parts.Count(); i++)
            {
                date = new DateModel();
                DateTime oDate = DateTime.ParseExact(parts[i], "dd/mm/yyyy", null);
                date.date = oDate;
                StringToList.Add(date);
            };

            return StringToList;
        }

        //GET
        public ActionResult Check()
        {
            List<DateModel> model = TempData["days"] as List<DateModel>;
            

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Check(List<DateModel> model)
        {

            String justificacion = TempData["justif"] as string;

            DateModel dateModel;
            List<TurnModel> turn;

            List<Day> daysRequested = new List<Day>();
            Day day = new Day();
            int fullDaysCount = 0;
            int midDaysCount = 0;


            //El sgte ciclo agarra los dias del modelo para crear una lista de Days con sus respectivos turnos
            //Realiza el conteo de los medios dias y dias completos para llenar la tabla request
            for (int index = 0; index < model.Count; index++)
            {
                dateModel = new DateModel();
                turn = new List<TurnModel>();
                dateModel = model.ElementAt(index);
                turn = dateModel.turn;

                day = new Day();

                if (turn.ElementAt(0).isChecked && turn.ElementAt(1).isChecked && turn.ElementAt(2).isChecked)
                {
                    day.turn = 1;
                    fullDaysCount++;

                }
                else if (turn.ElementAt(0).isChecked && !turn.ElementAt(1).isChecked && !turn.ElementAt(2).isChecked)
                {
                    day.turn = 2;
                    midDaysCount++;

                }
                else if (!turn.ElementAt(0).isChecked && turn.ElementAt(1).isChecked && !turn.ElementAt(2).isChecked)
                {
                    day.turn = 3;
                    midDaysCount++;
                }
                else if (!turn.ElementAt(0).isChecked && !turn.ElementAt(1).isChecked && turn.ElementAt(2).isChecked)
                {
                    day.turn = 4;
                    midDaysCount++;
                }
                else
                {

Vacations/Views/Request/Check.cshtml
@model List<Vacations.Models.DateModel>

@{
    /**/
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    /**/
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    /**/
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    /**/
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    /**/
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    /**/

    ViewBag.Title = "Create";
    Layout = (string)this.Session["Header"];
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {

        <h2>Solicitud de Vacaciones</h2>
        <label>Marque los turnos correspondientes</label>
        using (Html.BeginForm("Check", "Request", FormMethod.Post, htmlAttributes: new { @id = "myForm" }))
        {
            @Html.AntiForgeryToken()

            if (ViewBag.Message == "sent")
            {
                <script type="text/javascript">


                    $.alert({
                        title: 'Alert!',
                        content: 'Simple alert!',
                        theme: "modern"
                    });

                </script>

            }
            else if (!string.IsNullOrEmpty(ViewBag.Message))
            {

                <div class="alert-danger col-md-4">
                    @ViewBag.Message
                </div><br /><br />

            }
            <table class="table">
                @for (int index = 0; index < Model.Count; index++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(item => item[index].date)@Html.HiddenFor(item => item[index].date)
                        </td>
                        <td>
                            @for (int index2 = 0; index2 < Model[index].turn.Count; index2++)
                            {
                                <div class="col-md-10">
                                    @Html.HiddenFor(modelItem => Model[index].turn[index2].id)
                                    @Html.CheckBoxFor(modelItem => Model[index].turn[index2].isChecked)@Html.HiddenFor(modelItem => Model[index].turn[index2].isChecked)
                                    @Html.DisplayFor(modelItem => Model[index].turn[index2].label)@Html.HiddenFor(modelItem => Model[index].turn[index2].label)
                                </div>
                            }

                        </td>
                    </tr>

                }

            </table>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-default" id="btnConfirm" />
                </div>
            </div>
        }
    }
    <script>
        $(document).ready(function () {
            var button = $("#Send");
            button.click(function (event) {
                window.location = '/';
            })
        });


    </script>
}

Vacations/Views/Request/Confirm.cshtml
@{
    Layout = null;
}

<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Vacations/Views/Request/Create.cshtml
@model Vacations.Request
@{
    /**/

    ViewBag.Title = "Crear";
    HoliDays[] holiDaysDate = ViewBag.holidaysDate as HoliDays[];
    DateTime[] holidates = ViewBag.holidates as DateTime[];
    Layout = (string)this.Session["Header"];
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {

        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

            <script>
                // Ignore this in your implementation
                window.isMbscDemo = true;
            </script>


            <!-- Mobiscroll JS and CSS Includes -->
            <link rel="stylesheet" href="~/Content/Site.css">
            <script src="Scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
            <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>


            <style type="text/css">
                body {
                    margin: 0;
                    padding: 0;
                }
            </style>

        </head>


        <h2>Create</h2>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "Home")</a></li>
                <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
                <li class="breadcrumb-item active" aria-current="page">Vacaciones ></li>
            </ol>
        </nav>

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h2>Solicitud de Vacaciones</h2>

                <div>
                    @if (!string.IsNullOrEmpty(ViewBag.Message))
                    {
                        <div class="alert-danger col-md-4">
                            @ViewBag.Message
                        </div><br /><br />
                    }
                </div>
                <div class="container">
                    <div class="col-md-4 mx-auto">
                        <div class="form-group">
                            <label>Seleccione los días a solicitar</label>
                            @Html.HiddenFor(model => model.days, htmlAttributes: new { @id = "date", @type = "text", @class = "form-control date", @placeholder = "Elegir días", @autocomplete = "off" })
                        </div>
                        <div class="form-group">
                            <label>Ingrese una justificación para los días solicitados</label>
                            @Html.TextBoxFor(model => model.justificacion)
                            @Html.HiddenFor(model => model.justificacion)
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Confirmar" class="btn btn-default" id="btnConfirm" />
                        </div>
                    </div>
                </div>
            </div>


            

        }




        <div>
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
        @section scripts{
            <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
            <script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js'></script>
            <script src="~/Scripts/datepicker.js" type="text/javascript"></script>
            <script type="text/javascript">
            var holiDaysDate = @Html.Raw(Json.Encode(ViewBag.holidates));
            //var date = new Date(parseInt(holiDaysDate.counters.date));
            var freedays = []
            @foreach (var d in @ViewBag.holidates)
            {
                @:freedays.push("@d");
            }

            


            </script>

        }
    }
}

Vacations/Views/Request/FilterRequest.cshtml
@model List<Vacations.Models.RequestDTO>

@{
    ViewBag.Title = "MyVacation";
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
    Layout = (string)this.Session["Header"];

    int idPerson = (int)this.Session["idUser"];


}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>Mis solicitudes de vacaciones</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "Home")</a></li>
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vacaciones ></li>
            <li class="breadcrumb-item active" aria-current="page">Ver ></li>
        </ol>
    </nav>
    <h2>Mis solicitudes de vacaciones</h2>
    <div>
        <h4>Filtrar por estado</h4>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Todos", "MyVacation", "Request")</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("En espera", "FilterRequest", new { state = "sent" })</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Aceptado", "FilterRequest", new { state = "acepted" })</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Rechazadas", "FilterRequest", new { state = "rejected" })</button>
        </div>
    </div>

    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col" width="150">Fecha de solicitud</th>
                <th scope="col" width="150">Estado</th>
                <th scope="col" width="150">Motivo</th>
                <th scope="col" width="150">Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewData.Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.createdAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.state)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        <a asp-page="./Editar">
                            @Html.ActionLink("Editar", "Create", "Request")
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

Vacations/Views/Request/MyVacation.cshtml
@model List<Vacations.Models.RequestDTO>

@{
    ViewBag.Title = "MyVacation";
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
    Layout = (string)this.Session["Header"];

    int idPerson = (int)this.Session["idUser"];


}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>Mis solicitudes de vacaciones</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "Home")</a></li>
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vacaciones ></li>
            <li class="breadcrumb-item active" aria-current="page">Ver ></li>
        </ol>
    </nav>
    <h2>Mis solicitudes de vacaciones</h2>
    <div>
        <h4>Filtrar por estado</h4>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Todos", "MyVacation", "Request")</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("En espera", "FilterRequest", new { state = "sent" })</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Aceptado", "FilterRequest", new { state = "acepted" })</button>
            <button type="button" class="btn btn-secondary">@Html.ActionLink("Rechazadas", "FilterRequest", new { state = "rejected" })</button>
        </div>
    </div>

    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col" width="150">Fecha de solicitud</th>
                <th scope="col" width="150">Estado</th>
                <th scope="col" width="150">Motivo</th>
                <th scope="col" width="150">Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewData.Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.createdAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.state)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        <a asp-page="./Editar">
                            @Html.ActionLink("Editar", "UpdateDates", "Request")
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

Vacations/Views/Request/UpdateCheck.cshtml
@model List<Vacations.Models.DateModel>

@{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    ViewBag.Title = "Actualizar";
    Layout = (string)this.Session["Header"];
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {

        <h2>Solicitud de Vacaciones</h2>
        using (Html.BeginForm("UpdateCheck", "Request", FormMethod.Post, htmlAttributes: new { @id = "myForm" }))
        {
            @Html.AntiForgeryToken()

            if (ViewBag.Message == "sent")
            {
                <script type="text/javascript">


                    $.alert({
                        title: 'Alert!',
                        content: 'Simple alert!',
                        theme: "modern"
                    });

                </script>

            }
            else if (!string.IsNullOrEmpty(ViewBag.Message))
            {

                <div class="alert-danger col-md-4">
                    @ViewBag.Message
                </div><br /><br />

            }
            <table class="table">
                @for (int index = 0; index < Model.Count; index++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(item => item[index].date)@Html.HiddenFor(item => item[index].date)
                        </td>
                        <td>
                            @for (int index2 = 0; index2 < Model[index].turn.Count; index2++)
                            {
                                <div class="col-md-10">
                                    @Html.HiddenFor(modelItem => Model[index].turn[index2].id)
                                    @Html.CheckBoxFor(modelItem => Model[index].turn[index2].isChecked)@Html.HiddenFor(modelItem => Model[index].turn[index2].isChecked)
                                    @Html.DisplayFor(modelItem => Model[index].turn[index2].label)@Html.HiddenFor(modelItem => Model[index].turn[index2].label)
                                </div>
                            }

                        </td>
                    </tr>

                }

            </table>
            <input type="submit" value="Enviar" class="btn btn-default" onsubmit="openModal()" id="Send" />
        }
    }
            <script>
                $(document).ready(function () {
                    var button = $("#Send");
                    button.click(function (event) {
                        window.location = '/';
                    })
                });


            </script>
}