Vacations/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vacations.Controllers
{
   // [Authorize]
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Profile()
        {
            return View();
        }
    }
}

Vacations/Controllers/ServeRequestController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Vacations.Models;
using MimeKit;
using MailKit.Net.Smtp;

namespace Vacations.Controllers
{
    public class ServeRequestController : Controller
    {

        PersonController personController = new PersonController();

        public ActionResult Details(int requestId)
        {
            RequestDTO requestToFind = new RequestDTO();
            
            requestToFind = getRequestDetails(requestId);

            ViewData.Model = requestToFind;

            return View();
        }

        public ActionResult Serve()
        {
            List<RequestDTO> requestToList = new List<RequestDTO>();
            int idPerson = (int) this.Session["idUser"];
            requestToList = GetIncomingRequest(idPerson);


            ViewData.Model = requestToList;

            return View();
        }

        public ActionResult SendRequestAnswer(int requestIdToServe, string description, string state)
        {
            NotifyEmail (requestIdToServe,  description,  state);

            return View();
        }


        public RequestDTO getRequestDetails(int requestId)
        {
            RequestDTO requestToFind = new RequestDTO();
            List<DayDTO> requestDay = new List<DayDTO>();
            String depName="";

            using (EntitiesVacation entitiesVacation = new EntitiesVacation())
            {
          

                requestDay = (from day in entitiesVacation.Day
                              where day.RequestrequestId == requestId
                              select new DayDTO
                              {
                                  dayId = day.dayId,
                                  day1 = day.day1,
                                  turn = day.turn

                              }).ToList();
                
                    requestToFind = (from person in entitiesVacation.Person1
                                     join request in entitiesVacation.Request on person.personaId equals request.PersonpersonaId
                                     where request.requestId == requestId 
                                     select new RequestDTO
                                     {
                                         requestId = request.requestId,
                                         state = request.state,
                                         justificacion = request.justificacion,
                                         daysRequestedCount = request.daysRequestedCount,
                                         midDaysCount = request.midDaysCount,
                                         PersonpersonaId = request.PersonpersonaId,
                                         createdAt = request.createdAt,
                                         updatedAt = request.updatedAt,
                                         createdBy = request.createdBy,
                                         updatedBy = request.updatedBy,
                                         personName = person.name + " " + person.lastName
                                     }).FirstOrDefault();
                
                Person1 personLookFor = entitiesVacation.Person1
                                        .Where(per => per.personaId == requestToFind.PersonpersonaId).FirstOrDefault();
               

                if (personLookFor.RolrolId == 9)
                {
                    depName = (from dep in entitiesVacation.Departament
                     join person in entitiesVacation.Person1 
                     on dep.PersonpersonaId equals personLookFor.personaId
                     select dep.name).FirstOrDefault();
                }
                else if (personLookFor.RolrolId == 7)
                {
                    depName = (from dep in entitiesVacation.Departament
                     from person in dep.Person1
                     select dep.name).FirstOrDefault();
                }

                requestToFind.departmentName = depName;
                requestToFind.requestDays = GetTurnName(requestDay);

            }

            return requestToFind;
        }

        public List<DayDTO> GetTurnName (List<DayDTO> requestDay)
        {

            for (int i = 0; i < requestDay.Count; i++)
            {
                int turn = requestDay.ElementAt(i).turn;
            
            switch (turn)
            {
                case 1:
                     requestDay.ElementAt(i).turnName = "mañana";
                        break;

                case 2:
                        requestDay.ElementAt(i).turnName = "tarde";
                        break;

                    case 3:
                        requestDay.ElementAt(i).turnName = "noche";
                        break;

                    default:
                        requestDay.ElementAt(i).turnName = "día completo";
                        break;

                }

            }

            return requestDay;
        }

        public ActionResult DaysDetails(int requestId)
        {
            RequestDTO requestToFind = new RequestDTO();

            requestToFind = getRequestDetails(requestId);

            ViewData.Model = requestToFind.requestDays;

            return View();
        }


        public List<RequestDTO> GetIncomingRequest(int personId)
        {

            List<RequestDTO> requestList = new List<RequestDTO>();
            Departament department = new Departament();
            Person1 personSession = new Person1();


            using (EntitiesVacation entitiesVacation = new EntitiesVacation())
            {
                personSession = entitiesVacation.Person1
                                .Where(per => per.personaId == personId).FirstOrDefault();

                if (personSession.RolrolId == 8)
                {
                    requestList = (from person in entitiesVacation.Person1
                                   join request in entitiesVacation.Request on person.personaId equals request.PersonpersonaId
                                   where person.RolrolId == 9 & request.state == "sent"
                                   select new RequestDTO
                                   {
                                       requestId = request.requestId,
                                       state = request.state,
                                       description = request.description,
                                       daysRequestedCount = request.daysRequestedCount,
                                       midDaysCount = request.midDaysCount,
                                       PersonpersonaId = request.PersonpersonaId,
                                       createdAt = request.createdAt,
                                       updatedAt = request.updatedAt,
                                       createdBy = request.createdBy,
                                       updatedBy = request.updatedBy,
                                       personName = person.name + " " + person.lastName,
                                   }).ToList();
                }
                else
                {

                    department = entitiesVacation.Departament
                                 .Where(dep => dep.PersonpersonaId == personId).FirstOrDefault();

                    int idDepartamento = department.departamentId;

                    if (department != null)
                    {
                        requestList = (from d in entitiesVacation.Departament
                                       from person in d.Person1
                                       join request in entitiesVacation.Request on person.personaId equals request.PersonpersonaId
                                       where d.departamentId == idDepartamento & request.state == "sent"
                                       select new RequestDTO
                                       {
                                           requestId = request.requestId,
                                           state = request.state,
                                           description = request.description,
                                           daysRequestedCount = request.daysRequestedCount,
                                           midDaysCount = request.midDaysCount,
                                           PersonpersonaId = request.PersonpersonaId,
                                           createdAt = request.createdAt,
                                           updatedAt = request.updatedAt,
                                           createdBy = request.createdBy,
                                           updatedBy = request.updatedBy,
                                           personName = person.name + " " + person.lastName,
                                           departmentName = d.name
                                       }).ToList();


                       
                    }
                }
            }

            return requestList;

        }
        
        [HttpPost]
        public ActionResult NotifyEmail(int requestIdToServe, string description, string state)
        {
            var now = DateTime.Now;
            var updateDate = new DateTime(now.Year, now.Month, now.Day,
                                          now.Hour, now.Minute, now.Second);
            
            using (EntitiesVacation entitiesVacations = new EntitiesVacation())
            {
                Request request = entitiesVacations.Request.Where
                    (id => id.requestId == requestIdToServe).FirstOrDefault();

                request.description = description;
                request.state = state;
                request.updatedAt = updateDate;

                entitiesVacations.Entry(request).State = EntityState.Modified;
                entitiesVacations.SaveChanges();

Vacations/Views/ServeRequest/DaysDetails.cshtml
@model List<Vacations.Models.DayDTO>

@{
    ViewBag.Title = "Details";

    Layout = (string)this.Session["Header"];
    int i = 0;
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {

    }
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "HomeManager")</a></li>
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
            <li class="breadcrumb-item active" aria-current="page">Solicitudes ></li>
            <li class="breadcrumb-item active" aria-current="page">@Html.ActionLink("Atender Solicitudes >", "Serve", "ServeRequest")</li>
            <li class="breadcrumb-item active" aria-current="page">Detalles ></li>
            <li class="breadcrumb-item active" aria-current="page">Días solicitados ></li>
        </ol>
    </nav>
    <h2>Detalles de la solicitud</h2>
    <h4>Días solicitados</h4>

    <table class="table table-hover table-dark">
        <thead>

            <tr>
                <th scope="col" width="150">Fecha solicitada</th>
                <th scope="col" width="150">Turno(s)</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewData.Model)

            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem =>item.day1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.turnName)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        <FORM NAME="buttonbar">
            <INPUT class="bg-primary" TYPE="button" VALUE="Atrás" onClick="history.back()">
        </FORM>
    </div>
</body>
</html>

Vacations/Views/ServeRequest/Details.cshtml
@{
    ViewBag.Title = "Details";
    Vacations.Models.RequestDTO request = ViewData.Model;
    Layout = (string)this.Session["Header"];
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {
        

        <!DOCTYPE html>

        <html>
        <head>
            <meta name="viewport" content="width=device-width" />
            <title></title>


        </head>
        <body>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "HomeManager")</a></li>
                    <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Solicitudes ></li>
                    <li class="breadcrumb-item active" aria-current="page">@Html.ActionLink("Atender Solicitudes >", "Serve", "ServeRequest")</li>
                    <li class="breadcrumb-item active" aria-current="page">Detalles ></li>
                </ol>
            </nav>
            <h2>Detalles de la solicitud</h2>
            <div>
                <table class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <th scope="col" width="150">Solicitante</th>
                            <th scope="col" width="150">Departamento</th>
                            <th scope="col" width="150">Días solicitados</th>
                            <th scope="col" width="150">Motivo</th>
                            <th scope="col" width="150">Estado</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => request.personName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => request.departmentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => request.daysRequestedCount) |
                                <a asp-page="./Ver detalles">
                                    @Html.ActionLink("Ver detalles", "DaysDetails", new { request.requestId })
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => request.justificacion)
                            </td>
                            <td>
                                En espera
                            </td>
                        </tr>
                    </tbody>
                </table>

                <form action="~/ServeRequest/NotifyEmail" method="post">
                    <input type="number" name="requestIdToServe" id="requestIdToServe"
                           value="@request.requestId" style="visibility:hidden">
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <h4>Seleccione una opción para la solicitud</h4>
                                <select class="custom-select" id="state" name="state">
                                    <option value="acepted"> Aceptar</option>
                                    <option value="rejected"> Rechazar</option>
                                </select>
                            </div>
                        </div>
                        <h4>Ingrese el motivo por el cuál acepta u rechaza la solicitud</h4>
                        <textarea type="text" class="form-control" name="description" id="description" rows="3" cols="10" required></textarea>
                    </div>

                    <input type="submit" class="alert-info" value="Enviar">
                </form>

            </div>
            <div>
                <FORM NAME="buttonbar">
                    <INPUT class="bg-primary" TYPE="button" VALUE="Atrás" onClick="history.back()">
                </FORM>
            </div>
        </body>
    </html>
        }
    }

Vacations/Views/ServeRequest/Serve.cshtml
@model List<Vacations.Models.RequestDTO>

@{
    ViewBag.Title = "Serve";
    Layout = (string)this.Session["Header"];
    if (this.Session["rolUsuario"] == null)
    {
        Layout = "~/Views/Shared/_LayoutHome.cshtml";
        <h2>Vista no autorizada, por favor @Html.ActionLink("inicie sesion", "Index", "Home")</h2>
    }
    else
    {

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Inicio >", "Index", "HomeManager")</a></li>
            <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Perfil >", "Profile", "Profile")</a></li>
            <li class="breadcrumb-item active" aria-current="page">Solicitudes ></li>
            <li class="breadcrumb-item active" aria-current="page">Atender Solicitudes ></li>
        </ol>
    </nav>

    <h2>Lista de solicitudes de vacaciones</h2>
    
    <div>
        <table class="table table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">Solicitante</th>
                    <th scope="col">Fecha de solicitud</th>
                    <th scope="col">Detalles</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewData.Model)

                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.requestId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.personName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.createdAt)
                    </td>
                    <td>
                        <a asp-page="./Ver más">
                            @Html.ActionLink("Details", "Details", new { requestId = item.requestId })

                        </a>
                    </td>
                </tr>
                }


            </tbody>
        </table>

    </div>
</body>
</html>
        }
    }